# Generated by Django 4.1.1 on 2022-12-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carwash", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
