# Generated by Django 4.1.1 on 2022-12-23 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carwash", "0002_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="carwash.bookingstatus",
                verbose_name="booking status",
            ),
        ),
    ]
