# Generated by Django 4.1.1 on 2022-12-24 00:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carwash", "0003_alter_booking_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarWashService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=40, verbose_name="carwash service"),
                ),
                ("price", models.IntegerField(default=100, verbose_name="price")),
            ],
        ),
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 12, 24, 5, 57, 13, 66472),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="carwashplace",
            name="services",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="carwash.carwashservice",
                verbose_name="services",
            ),
        ),
    ]
