# Generated by Django 4.1.1 on 2022-12-24 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carwash", "0004_carwashservice_alter_booking_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 12, 24, 6, 2, 21, 49641),
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="carwashplace",
            name="services",
        ),
        migrations.AddField(
            model_name="carwashplace",
            name="services",
            field=models.ManyToManyField(
                null=True, to="carwash.carwashservice", verbose_name="services"
            ),
        ),
    ]
