# Generated by Django 4.1.1 on 2022-12-24 00:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carwash", "0006_booking_service_alter_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 12, 24, 6, 6, 56, 715449),
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="booking",
            name="service",
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="carwash.bookingstatus",
                verbose_name="booking status",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="carwash.carwashservice",
                verbose_name="services",
            ),
        ),
    ]
