# Generated by Django 4.1.1 on 2022-12-24 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carwash", "0009_alter_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 12, 24, 6, 11, 33, 167036),
                null=True,
            ),
        ),
    ]
