# Generated by Django 4.1.1 on 2022-12-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carwash", "0012_alter_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carwashplace",
            name="services",
            field=models.ManyToManyField(
                to="carwash.carwashservice", verbose_name="services"
            ),
        ),
    ]
