# Generated by Django 4.1.1 on 2022-12-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carwash", "0013_alter_carwashplace_services"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carwashplace",
            name="slots_available",
        ),
    ]
