# Generated by Django 4.1.1 on 2022-12-24 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carwash", "0014_remove_carwashplace_slots_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="carwashplace",
            name="slots",
            field=models.IntegerField(default=5, verbose_name="slots available today"),
        ),
        migrations.AddField(
            model_name="carwashplace",
            name="slots_last_refresh",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 24, 11, 24, 30, 174539, tzinfo=datetime.timezone.utc
                ),
                verbose_name="slots refreshed on",
            ),
        ),
    ]
