# Generated by Django 4.1.1 on 2022-12-24 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carwash", "0015_carwashplace_slots_carwashplace_slots_last_refresh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carwashplace",
            name="slots_last_refresh",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 24, 11, 31, 44, 252525, tzinfo=datetime.timezone.utc
                ),
                verbose_name="slots refreshed on",
            ),
        ),
    ]
